listen = "127.0.0.1:8080"
admin_listen = "192.168.1.10:8081"
engine_url = "http://192.168.1.11:10101"
public_base_url = "https://tts.markn2000.com"
api_revision = "v2"

default_id = "1878365376"

cache_dir = "./cache"
cache_days = 31
cache_max_mb = 1024
cache_revision = 1

ffmpeg_path = "ffmpeg"
codec = "vorbis"
bitrate_kbps = 48
